// environment.js
// Survival VR - Environment System
//
// Controls:
// - Sky
// - Sun
// - Moon
// - Day/night lighting
// - Water animation
// - Wind
// - Grass movement
// - Clouds
// - Environment ambience
//
// Designed to work with the seeded world generated by world.js.

const {
  THREE,
  GAME,
  gameEvent
} = window.SurvivalVR;

// ------------------------------------------------------------
// STATE
// ------------------------------------------------------------

const environmentState = {
  initialized: false,

  sun: null,
  moon: null,

  sky: null,
  water: null,

  clouds: [],
  grass: [],

  waterTime: 0,
  windTime: 0,

  dayNightSpeed: 1,

  currentPeriod: "day",

  lastDay: 1,
  lastTime: 8,

  windDirection: 0,
  windStrength: 0.35,

  waterBaseY: -0.15,

  environmentGroup: null
};

// ------------------------------------------------------------
// HELPERS
// ------------------------------------------------------------

function getScene() {
  return window.SurvivalVR.scene;
}

function getRenderer() {
  return window.SurvivalVR.renderer;
}

function clamp(
  value,
  min,
  max
) {
  return Math.max(
    min,
    Math.min(
      max,
      value
    )
  );
}

// ------------------------------------------------------------
// ENVIRONMENT GROUP
// ------------------------------------------------------------

function createEnvironmentGroup() {
  const scene =
    getScene();

  if (!scene) {
    return null;
  }

  if (
    environmentState.environmentGroup
  ) {
    scene.remove(
      environmentState.environmentGroup
    );
  }

  environmentState.environmentGroup =
    new THREE.Group();

  environmentState.environmentGroup.name =
    "Environment";

  scene.add(
    environmentState.environmentGroup
  );

  return environmentState.environmentGroup;
}

// ------------------------------------------------------------
// SKY
// ------------------------------------------------------------

function createSky() {
  const scene =
    getScene();

  if (!scene) {
    return;
  }

  if (
    environmentState.sky
  ) {
    scene.remove(
      environmentState.sky
    );
  }

  const geometry =
    new THREE.SphereGeometry(
      140,
      32,
      20
    );

  const material =
    new THREE.MeshBasicMaterial({
      color: 0x87ceeb,
      side: THREE.BackSide,
      depthWrite: false
    });

  const sky =
    new THREE.Mesh(
      geometry,
      material
    );

  sky.name =
    "Sky";

  environmentState.sky =
    sky;

  scene.add(
    sky
  );
}

// ------------------------------------------------------------
// SUN
// ------------------------------------------------------------

function createSun() {
  const scene =
    getScene();

  if (!scene) {
    return;
  }

  const sun =
    new THREE.DirectionalLight(
      0xffffff,
      2.2
    );

  sun.name =
    "Sun";

  sun.castShadow =
    true;

  sun.shadow.mapSize.width =
    1024;

  sun.shadow.mapSize.height =
    1024;

  sun.shadow.camera.near =
    1;

  sun.shadow.camera.far =
    120;

  sun.shadow.camera.left =
    -45;

  sun.shadow.camera.right =
    45;

  sun.shadow.camera.top =
    45;

  sun.shadow.camera.bottom =
    -45;

  sun.position.set(
    20,
    35,
    10
  );

  scene.add(
    sun
  );

  environmentState.sun =
    sun;

  window.SurvivalVR.sun =
    sun;
}

// ------------------------------------------------------------
// MOON
// ------------------------------------------------------------

function createMoon() {
  const scene =
    getScene();

  if (!scene) {
    return;
  }

  const moon =
    new THREE.DirectionalLight(
      0x9bbcff,
      0
    );

  moon.name =
    "Moon";

  moon.position.set(
    -20,
    25,
    -15
  );

  scene.add(
    moon
  );

  environmentState.moon =
    moon;

  window.SurvivalVR.moon =
    moon;
}

// ------------------------------------------------------------
// AMBIENT LIGHT
// ------------------------------------------------------------

function createAmbientLight() {
  const scene =
    getScene();

  if (!scene) {
    return;
  }

  const existing =
    scene.getObjectByName(
      "SurvivalAmbientLight"
    );

  if (existing) {
    scene.remove(
      existing
    );
  }

  const ambient =
    new THREE.HemisphereLight(
      0xbfe9ff,
      0x29402b,
      1.15
    );

  ambient.name =
    "SurvivalAmbientLight";

  scene.add(
    ambient
  );

  window.SurvivalVR.ambientLight =
    ambient;
}

// ------------------------------------------------------------
// CLOUDS
// ------------------------------------------------------------

function createCloud(
  x,
  y,
  z,
  scale
) {
  const group =
    new THREE.Group();

  group.position.set(
    x,
    y,
    z
  );

  group.scale.setScalar(
    scale
  );

  const material =
    new THREE.MeshLambertMaterial({
      color: 0xffffff,
      transparent: true,
      opacity: 0.78
    });

  const pieces = [
    {
      x: 0,
      y: 0,
      z: 0,
      r: 2.5
    },
    {
      x: 2.2,
      y: 0.4,
      z: 0,
      r: 2
    },
    {
      x: -2.2,
      y: 0.3,
      z: 0,
      r: 2
    },
    {
      x: 0.8,
      y: 1,
      z: 0,
      r: 1.8
    }
  ];

  for (
    const piece
    of pieces
  ) {
    const mesh =
      new THREE.Mesh(
        new THREE.SphereGeometry(
          piece.r,
          12,
          8
        ),
        material
      );

    mesh.position.set(
      piece.x,
      piece.y,
      piece.z
    );

    group.add(
      mesh
    );
  }

  group.userData.speed =
    0.3 +
    Math.random() *
      0.25;

  group.userData.startX =
    x;

  return group;
}

function createClouds() {
  const group =
    environmentState.environmentGroup;

  if (!group) {
    return;
  }

  environmentState.clouds =
    [];

  for (
    let i = 0;
    i < 7;
    i++
  ) {
    const cloud =
      createCloud(
        -60 +
          i * 20,
        35 +
          (i % 3) * 5,
        -40 +
          (i % 4) * 22,
        1.3 +
          (i % 3) * 0.35
      );

    group.add(
      cloud
    );

    environmentState.clouds.push(
      cloud
    );
  }
}

// ------------------------------------------------------------
// WATER
// ------------------------------------------------------------

function createWater() {
  const scene =
    getScene();

  if (!scene) {
    return;
  }

  if (
    environmentState.water
  ) {
    scene.remove(
      environmentState.water
    );
  }

  const worldData =
    window.SurvivalVR.worldData;

  const lake =
    worldData?.lake || {
      x: 9,
      z: -7,
      radius: 9
    };

  const geometry =
    new THREE.CircleGeometry(
      lake.radius,
      48
    );

  const material =
    new THREE.MeshPhongMaterial({
      color: 0x287f91,
      transparent: true,
      opacity: 0.78,
      shininess: 90,
      side: THREE.DoubleSide
    });

  const water =
    new THREE.Mesh(
      geometry,
      material
    );

  water.rotation.x =
    -Math.PI / 2;

  water.position.set(
    lake.x,
    environmentState.waterBaseY,
    lake.z
  );

  water.name =
    "IslandLake";

  water.userData.baseY =
    environmentState.waterBaseY;

  water.userData.lake =
    lake;

  scene.add(
    water
  );

  environmentState.water =
    water;

  window.SurvivalVR.water =
    water;
}

// ------------------------------------------------------------
// WATER RIPPLES
// ------------------------------------------------------------

function createWaterRipples() {
  const water =
    environmentState.water;

  if (!water) {
    return;
  }

  const lake =
    water.userData.lake;

  if (!lake) {
    return;
  }

  if (
    water.userData.ripples
  ) {
    return;
  }

  const rippleGroup =
    new THREE.Group();

  rippleGroup.name =
    "WaterRipples";

  const material =
    new THREE.MeshBasicMaterial({
      color: 0x8dd9e6,
      transparent: true,
      opacity: 0.2,
      side: THREE.DoubleSide
    });

  for (
    let i = 0;
    i < 8;
    i++
  ) {
    const radius =
      0.5 +
      (i % 4) * 0.35;

    const geometry =
      new THREE.RingGeometry(
        radius,
        radius + 0.035,
        24
      );

    const ripple =
      new THREE.Mesh(
        geometry,
        material.clone()
      );

    const angle =
      (i / 8) *
      Math.PI *
      2;

    const distance =
      lake.radius *
      0.55;

    ripple.position.set(
      lake.x +
        Math.cos(angle) *
          distance,
      environmentState.waterBaseY +
        0.025,
      lake.z +
        Math.sin(angle) *
          distance
    );

    ripple.rotation.x =
      -Math.PI / 2;

    ripple.userData.phase =
      i * 0.8;

    rippleGroup.add(
      ripple
    );
  }

  water.userData.ripples =
    rippleGroup;

  getScene().add(
    rippleGroup
  );
}

// ------------------------------------------------------------
// GRASS
// ------------------------------------------------------------

function registerGrassObjects() {
  const scene =
    getScene();

  if (!scene) {
    return;
  }

  environmentState.grass =
    [];

  scene.traverse(
    object => {
      if (
        object.userData &&
        object.userData.isGrass
      ) {
        environmentState.grass.push(
          object
        );
      }
    }
  );
}

// ------------------------------------------------------------
// WIND
// ------------------------------------------------------------

function updateWind(
  delta
) {
  environmentState.windTime +=
    delta;

  const strength =
    clamp(
      Number(
        GAME.environment
          ?.wind
          ?.strength
      ) || 0.35,
      0,
      2
    );

  environmentState.windStrength =
    strength;

  const direction =
    Number(
      GAME.environment
        ?.wind
        ?.direction
    ) || 0;

  environmentState.windDirection =
    direction;

  const windX =
    Math.cos(
      direction
    ) *
    strength;

  const windZ =
    Math.sin(
      direction
    ) *
    strength;

  for (
    const grass
    of environmentState.grass
  ) {
    if (
      !grass ||
      !grass.userData
    ) {
      continue;
    }

    const phase =
      grass.userData.windPhase ||
      0;

    const amount =
      Math.sin(
        environmentState.windTime *
          2.2 +
          phase
      ) *
      0.035 *
      strength;

    grass.rotation.z =
      amount *
      windX;

    grass.rotation.x =
      amount *
      windZ;
  }

  for (
    const cloud
    of environmentState.clouds
  ) {
    if (!cloud) {
      continue;
    }

    cloud.position.x +=
      cloud.userData.speed *
      delta;

    if (
      cloud.position.x >
      75
    ) {
      cloud.position.x =
        -75;
    }
  }
}

// ------------------------------------------------------------
// WATER UPDATE
// ------------------------------------------------------------

function updateWater(
  delta
) {
  const water =
    environmentState.water;

  if (!water) {
    return;
  }

  environmentState.waterTime +=
    delta;

  const wave =
    Math.sin(
      environmentState.waterTime *
        1.6
    ) *
    0.035;

  water.position.y =
    water.userData.baseY +
    wave;

  const ripples =
    water.userData.ripples;

  if (!ripples) {
    return;
  }

  for (
    const ripple
    of ripples.children
  ) {
    const phase =
      ripple.userData.phase ||
      0;

    const scale =
      1 +
      Math.sin(
        environmentState.waterTime *
          1.5 +
          phase
      ) *
      0.08;

    ripple.scale.setScalar(
      scale
    );

    ripple.material.opacity =
      0.12 +
      Math.sin(
        environmentState.waterTime *
          1.4 +
          phase
      ) *
      0.06;
  }
}

// ------------------------------------------------------------
// DAY / NIGHT
// ------------------------------------------------------------

function getTimeOfDay() {
  const time =
    Number(
      GAME.world?.time
    );

  if (
    !Number.isFinite(
      time
    )
  ) {
    return 8;
  }

  return (
    (time % 24 + 24) %
    24
  );
}

function getSunAngle(
  time
) {
  /*
   * 0 = midnight
   * 6 = sunrise
   * 12 = noon
   * 18 = sunset
   * 24 = midnight
   */

  return (
    ((time - 6) / 24) *
    Math.PI *
    2
  );
}

function updateDayNight() {
  const time =
    getTimeOfDay();

  const angle =
    getSunAngle(
      time
    );

  const sun =
    environmentState.sun;

  const moon =
    environmentState.moon;

  const ambient =
    window.SurvivalVR
      .ambientLight;

  /*
   * Circular sun movement.
   */
  const sunX =
    Math.cos(angle) *
    45;

  const sunY =
    Math.sin(angle) *
    45;

  const sunZ =
    12;

  if (sun) {
    sun.position.set(
      sunX,
      sunY,
      sunZ
    );
  }

  if (moon) {
    moon.position.set(
      -sunX,
      -sunY + 5,
      -sunZ
    );
  }

  /*
   * Daylight strength.
   */
  const daylight =
    clamp(
      Math.sin(angle),
      0,
      1
    );

  const sunriseFade =
    clamp(
      daylight * 1.3,
      0,
      1
    );

  if (sun) {
    sun.intensity =
      0.25 +
      sunriseFade *
        2.0;
  }

  if (moon) {
    moon.intensity =
      0.03 +
      (1 - sunriseFade) *
        0.28;
  }

  if (ambient) {
    ambient.intensity =
      0.38 +
      sunriseFade *
        0.85;
  }

  updateSkyColor(
    time,
    daylight
  );

  const period =
    getPeriod(
      time
    );

  if (
    period !==
    environmentState.currentPeriod
  ) {
    const oldPeriod =
      environmentState.currentPeriod;

    environmentState.currentPeriod =
      period;

    gameEvent(
      "environment-period-changed",
      {
        oldPeriod,
        period,
        time
      }
    );

    if (
      period ===
      "night"
    ) {
      gameEvent(
        "survival-night-started"
      );
    }

    if (
      period ===
      "day"
    ) {
      gameEvent(
        "survival-new-day"
      );
    }
  }
}

function getPeriod(
  time
) {
  if (
    time >= 5 &&
    time < 8
  ) {
    return "sunrise";
  }

  if (
    time >= 8 &&
    time < 17
  ) {
    return "day";
  }

  if (
    time >= 17 &&
    time < 20
  ) {
    return "sunset";
  }

  return "night";
}

// ------------------------------------------------------------
// SKY COLOR
// ------------------------------------------------------------

function updateSkyColor(
  time,
  daylight
) {
  const sky =
    environmentState.sky;

  if (!sky) {
    return;
  }

  let color;

  if (
    time >= 6 &&
    time < 8
  ) {
    color =
      new THREE.Color(
        0xf2b36f
      );
  } else if (
    time >= 8 &&
    time < 17
  ) {
    color =
      new THREE.Color(
        0x70bde8
      );
  } else if (
    time >= 17 &&
    time < 20
  ) {
    color =
      new THREE.Color(
        0xe98763
      );
  } else {
    color =
      new THREE.Color(
        0x08182b
      );
  }

  sky.material.color.lerp(
    color,
    0.08
  );
}

// ------------------------------------------------------------
// TIME ADVANCEMENT
// ------------------------------------------------------------

function updateWorldTime(
  delta
) {
  if (
    !GAME.state?.started ||
    GAME.state?.paused ||
    GAME.state?.gameOver
  ) {
    return;
  }

  /*
   * One real second equals
   * approximately one game minute.
   */
  const gameMinutes =
    delta *
    environmentState.dayNightSpeed;

  let time =
    getTimeOfDay();

  time +=
    gameMinutes /
    60;

  let day =
    Number(
      GAME.world?.day
    ) || 1;

  if (
    time >= 24
  ) {
    time -= 24;
    day++;

    GAME.statistics.daysSurvived =
      Math.max(
        GAME.statistics.daysSurvived || 0,
        day - 1
      );
  }

  if (
    typeof window.SurvivalVR
      .setWorldTime ===
    "function"
  ) {
    window.SurvivalVR
      .setWorldTime(
        time
      );
  } else {
    GAME.world.time =
      time;
  }

  if (
    typeof window.SurvivalVR
      .setWorldDay ===
    "function"
  ) {
    window.SurvivalVR
      .setWorldDay(
        day
      );
  } else {
    GAME.world.day =
      day;
  }
}

// ------------------------------------------------------------
// ENVIRONMENT INITIALIZATION
// ------------------------------------------------------------

function initializeEnvironment() {
  if (
    environmentState.initialized
  ) {
    return;
  }

  if (!getScene()) {
    return;
  }

  createEnvironmentGroup();

  createSky();

  createSun();

  createMoon();

  createAmbientLight();

  createClouds();

  createWater();

  createWaterRipples();

  registerGrassObjects();

  updateDayNight();

  environmentState.initialized =
    true;

  console.log(
    "[SurvivalVR] Environment initialized"
  );
}

// ------------------------------------------------------------
// REBUILD ENVIRONMENT
// ------------------------------------------------------------

function rebuildEnvironment() {
  initializeEnvironment();

  createWater();

  createWaterRipples();

  registerGrassObjects();

  updateDayNight();
}

// ------------------------------------------------------------
// UPDATE
// ------------------------------------------------------------

function update(
  delta
) {
  if (
    !environmentState.initialized
  ) {
    initializeEnvironment();
  }

  updateWorldTime(
    delta
  );

  updateDayNight();

  updateWater(
    delta
  );

  updateWind(
    delta
  );
}

// ------------------------------------------------------------
// SETTINGS
// ------------------------------------------------------------

function applySettings(
  settings
) {
  if (!settings) {
    return;
  }

  if (
    settings.shadows !==
    undefined
  ) {
    const renderer =
      getRenderer();

    if (renderer) {
      renderer.shadowMap.enabled =
        Boolean(
          settings.shadows
        );
    }

    if (
      environmentState.sun
    ) {
      environmentState.sun.castShadow =
        Boolean(
          settings.shadows
        );
    }
  }

  if (
    settings.graphicsQuality
  ) {
    applyGraphicsQuality(
      settings.graphicsQuality
    );
  }
}

function applyGraphicsQuality(
  quality
) {
  const renderer =
    getRenderer();

  if (!renderer) {
    return;
  }

  if (
    quality ===
    "low"
  ) {
    renderer.setPixelRatio(
      Math.min(
        window.devicePixelRatio ||
          1,
        1
      )
    );
  } else if (
    quality ===
    "high"
  ) {
    renderer.setPixelRatio(
      Math.min(
        window.devicePixelRatio ||
          1,
        2
      )
    );
  } else {
    renderer.setPixelRatio(
      Math.min(
        window.devicePixelRatio ||
          1,
        1.5
      )
    );
  }
}

// ------------------------------------------------------------
// EVENT SETUP
// ------------------------------------------------------------

function setupEvents() {
  window.addEventListener(
    "survival-world-generated",
    () => {
      rebuildEnvironment();
    }
  );

  window.addEventListener(
    "survival-new-world-created",
    () => {
      rebuildEnvironment();
    }
  );

  window.addEventListener(
    "survival-settings-changed",
    event => {
      applySettings(
        event.detail ||
          GAME.settings
      );
    }
  );
}

// ------------------------------------------------------------
// SYSTEM OBJECT
// ------------------------------------------------------------

const environmentSystem = {
  state:
    environmentState,

  initialize:
    initializeEnvironment,

  rebuild:
    rebuildEnvironment,

  update,

  applySettings,

  getPeriod: () =>
    getPeriod(
      getTimeOfDay()
    ),

  getTime: getTimeOfDay,

  getWater: () =>
    environmentState.water,

  getSun: () =>
    environmentState.sun,

  getMoon: () =>
    environmentState.moon,

  getWind: () => ({
    direction:
      environmentState.windDirection,
    strength:
      environmentState.windStrength
  })
};

// ------------------------------------------------------------
// REGISTER
// ------------------------------------------------------------

window.SurvivalVR.systems.environment =
  environmentSystem;

window.SurvivalVR.environment =
  environmentSystem;

// ------------------------------------------------------------
// EVENTS
// ------------------------------------------------------------

setupEvents();

// ------------------------------------------------------------
// INITIALIZE
// ------------------------------------------------------------

initializeEnvironment();

export {
  environmentSystem,
  initializeEnvironment,
  rebuildEnvironment
};